services:
  - type: web
    name: studysync-backend
    env: docker
    plan: free
    region: frankfurt
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: studysync-db
          property: connectionString
databases:
  - name: studysync-db
